

services:
  database:
    build: ./database
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    networks:
      - spring_net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
      - frontend_net
    depends_on:
      - database



  frontend:
    build: ./frontend
    container_name: frontend
    ports:
     - 3000:3000
    networks:
     - frontend_net

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
     - 3001:3000  
    networks:
     - frontend_net


networks:
  spring_net:
  frontend_net: