name: Notify Telegram

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Push Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          REPO="${{ github.repository }}"
          AUTHOR="${{ github.actor }}"
          BRANCH="${{ github.ref_name }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"

          MESSAGE="🚀 *New Push Alert*\n\n📁 *Repository:* ${REPO}\n👤 *Author:* ${AUTHOR}\n🌿 *Branch:* ${BRANCH}\n📝 *Message:* ${COMMIT_MSG}\n🔗 [View Commit](${COMMIT_URL})"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"
